### ISSUE TITLE
Release with kxserialization 1.0.0-RC 

### ISSUE THREAD

**Issue by Shusshu** [joffrey-bion/krossbow#61] opened 2020-08-19 15:16 UTC
Hello,

Could you cut a release with the latest version (because kotlin 1.4.0 will not work with serialisation 0.20.0)?

**Comment by Shusshu** [comment] 2020-08-29 09:18
bump

**Comment by joffrey-bion** [comment] 2020-08-30 17:18
Hey, thanks for your issue, and sorry I somehow missed the notification.
I'm actually in the process of doing the migration.
I will release as soon as possible with Kotlin 1.4 and serialization 1.0.0-RC.
I was hoping for a 1.0.0 release of Kx Serialization first, but if it doesn't come out soon I guess it's better to at least have something with the RC.

**Comment by joffrey-bion** [comment] 2020-08-30 17:28
Closing as duplicate of wider https://github.com/joffrey-bion/krossbow/issues/62

**Closed by joffrey-bion** 2020-08-30 17:28 UTC
Labels: duplicate

**Comment by joffrey-bion** [comment] 2020-08-31 16:01
@Shusshu I released today 0.30.1 with fixed metadata issues. It includes migration to Kotlin 1.4, Serialization 1.0.0-RC, and Coroutines 1.3.9. Please let me know if you have any issue with it.

Sorry again for the absence of reply for a while, for some reason my notifications were disabled (repo was not "watched").

**Comment by Shusshu** [comment] 2020-09-01 08:31
@joffrey-bion Thanks! works well
