### ISSUE TITLE
Missing hearbeats ignore auto reconnect

### ISSUE THREAD

**Issue by TimOrtel** [joffrey-bion/krossbow#285] opened 2022-12-05 19:56 UTC
A missing hearbeat closes the stomp socket which in turn closes the krossbow-reconnection-watcher. Therefore, if the device loses connection, e.g. because WLAN gets switched off, the reconnection does not happen. I tested this on Android with version 4.5.0

**Comment by joffrey-bion** [comment] 2022-12-05 23:01
I think you're experiencing https://github.com/joffrey-bion/krossbow/issues/102. The auto-reconnection is for now only a web socket level feature, and the STOMP client doesn't take advantage of it. I'm closing this as a duplicate of that issue, which is already here to track the support for reconnections at STOMP level

**Closed by joffrey-bion** 2022-12-05 23:01 UTC
Labels: bug
