### ISSUE TITLE
KMM iOS app build error when dependency "krossbow-stomp-kxserialization" added

### ISSUE THREAD

**Issue by hyangilam** [joffrey-bion/krossbow#231] opened 2022-06-08 01:35 UTC
Hello Joffrey, I wanted to use "krossbow-stomp-kxserialization" from KMM iOS App, but there is build error.

> Task :shared:linkPodDebugFrameworkIosArm64 FAILED
e: Could not find "org.jetbrains.kotlinx:kotlinx-serialization-json" in [/Users/xxx/AndroidStudioProjects/kmmTest/iosApp/Pods, /Users/xxx/.konan/klib, /Users/xxx/.konan/kotlin-native-prebuilt-macos-x86_64-1.6.21/klib/common, /Users/xxx/.konan/kotlin-native-prebuilt-macos-x86_64-1.6.21/klib/platform/ios_arm64]

From Android Studio KMM app template, I just added the dependency below

<img width="834" alt="Screen Shot 2022-06-08 at 10 34 26 AM" src="https://user-images.githubusercontent.com/3990982/172512274-b2a5e2c1-765b-48bc-9483-e0009d23c18e.png">
 
How could I solve this error? Does "krossbow-stomp-kxserialization" not support the iOS yet?
Thank you in advance

**Comment by joffrey-bion** [comment] 2022-06-08 07:13
Hi, thanks a lot for reporting this.

It is supposed to be supported, so if it fails like this, it's a bug.

It might be due to the `compileOnly` dependency on Kotlinx Serialization Json which I haven't solved yet. Sorry about that.

I will look into it and deliver a fix ASAP

**Comment by joffrey-bion** [comment] 2022-06-08 11:29
Reproduced here: https://github.com/joffrey-bion/krossbow-reproducer-231/runs/6792493326?check_suite_focus=true#step:4:80

**Comment by joffrey-bion** [comment] 2022-06-08 12:25
@hyangilam this might be due to this bug: https://youtrack.jetbrains.com/issue/KT-46377

A workaround is to add the following to your `gradle.properties` (seems to work on my reproducer project):
```
kotlin.native.cacheKind=none
```

I will try to release a version that doesn't rely on `compileOnly` in the future, but this will not be obvious in terms of backwards compatibility.

**Comment by joffrey-bion** [comment] 2022-06-08 12:50
Cool! I'm happy that it's solved for you!

> How do you find it so fast? :)

Well there is a warning in Krossbow's build about this `compileOnly` dependency on `kotlinx-serialization-json`, and it has bugged me for a while, so I immediately thought about this 😄 

But I could never figure out so far if this is an actual problem, and I don't have a mac to test this. So I let it slide so far. Now that you pointed out the error, it helped me quite a bit and I could find the issue on Kotlin's YouTrack quickly with the right keywords.

So thanks!

**Comment by joffrey-bion** [comment] 2022-06-10 10:06
Closing this issue in favor of https://github.com/joffrey-bion/krossbow/issues/237

**Closed by joffrey-bion** 2022-06-10 10:06 UTC
Labels: bug
