### ISSUE TITLE
OkHttp websocket throws java.io.EOFException after 1 minute

### ISSUE THREAD

**Issue by chengxinping** [joffrey-bion/krossbow#128] opened 2021-07-28 08:31 UTC
![image](https://user-images.githubusercontent.com/18040985/127290699-3aeecff4-1f14-4bb5-9d1d-4fa6b1ff1e79.png)

I just connect and subscribe，but when I stop one minute ，it will crash

**Comment by chengxinping** [comment] 2021-07-28 08:32
it cause by heart beat?

**Comment by joffrey-bion** [comment] 2021-07-28 11:04
Hi @chengxinping, thanks for opening this issue.

I'm sorry but I have very little information here. The issue template for bug reports lists what information I need to properly investigate bugs, like a way to reproduce, artifacts used, library version, kotlin version, etc. Here it looks like you removed the whole structure and did not provide the information, so I am missing a few things. 

I'm assuming you're using `krossbow-stomp-core` with the OkHttp-based webocket implementation (`krossbow-websocket-okhttp`). Is this correct?

Could you please tell me which version of OkHttp you are using? (If you specified one yourself)

Also, please provide the full stacktrace, because the cause is truncated here, so I don't know which part of the Okio/OkHttp internals is failing.

> it cause by heart beat?

Heart beats are not enabled by default. Did you enable them? Could you please share your STOMP config?

Thanks a lot in advance for the extra information

**Comment by yunjaena** [comment] 2021-09-14 09:12
@joffrey-bion 
I had a same problem and found some solution this work for me.

[ok http client ping interval](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/ping-interval/)
[Related issue 1](https://github.com/square/okhttp/issues/3197)
[Related issue 2](https://github.com/square/okhttp/issues/803)

``` kotlin
  OkHttpClient.Builder().apply {
            connectTimeout(10, TimeUnit.SECONDS)
            readTimeout(30, TimeUnit.SECONDS)
            writeTimeout(15, TimeUnit.SECONDS)
            addInterceptor(getHttpLoggingInterceptor())
            pingInterval(10L, TimeUnit.SECONDS)  
        }.build()
```

Thank you making wonderful library :)

**Comment by joffrey-bion** [comment] 2021-09-14 09:47
@yunjaena thanks a lot for the additional info and workaround! Could you please share which version of OkHttp you were using when you got the bug? Did you use the one embedded with Krossbow, or did you declare a specific one in your project?

Also, which version of Krossbow were you using at that time?

**Comment by yunjaena** [comment] 2021-09-14 10:13
@joffrey-bion 

Library version

```groovy
    /* Dependency - STOMP_ crossbow */
    def stomp_version = "2.5.0"
    stomp = "org.hildan.krossbow:krossbow-stomp-core:$stomp_version"
    stompOkhttp = "org.hildan.krossbow:krossbow-websocket-okhttp:$stomp_version"

    /* Dependency - okhttp */
    def okhttp_version = "3.12.0"
    okhttp = "com.squareup.okhttp3:okhttp:$okhttp_version"
```

Inject StompClient by Koin library and use OkHttpClient that declared one

```kotlin
factory {
        StompClient(OkHttpWebSocketClient(get(named(AUTH))))
    }

 factory(named(AUTH)) {
        OkHttpClient.Builder().apply {
            connectTimeout(10, TimeUnit.SECONDS)
            readTimeout(30, TimeUnit.SECONDS)
            writeTimeout(15, TimeUnit.SECONDS)
            addInterceptor(getHttpLoggingInterceptor())
            pingInterval(10L, TimeUnit.SECONDS)
            addInterceptor { chain ->
                val accessToken = Hawk.get(ACCESS_TOKEN, "")
                Logger.d("access token : $accessToken")
                val newRequest: Request = chain.request().newBuilder()
                    .addHeader("Authorization", "Bearer $accessToken")
                    .build()
                chain.proceed(newRequest)
            }
        }.build()
    }
```

**Comment by joffrey-bion** [comment] 2021-09-14 10:55
Thank you very much for this. So the problem was that the server was timing out after 1 min, and was solved by enabling pings, is this correct?

**Comment by yunjaena** [comment] 2021-09-14 11:21
@joffrey-bion yes right :)

**Comment by joffrey-bion** [comment] 2021-09-14 11:38
There is already a reconnection feature at websocket level (see https://github.com/joffrey-bion/krossbow/issues/94), but it's not really ready to use in combination with STOMP client, because we need to automatically re-subscribe all subscriptions as well.

This extra work is tracked here: https://github.com/joffrey-bion/krossbow/issues/102

**Comment by yunjaena** [comment] 2021-09-14 11:55
I see, so the first solution is little bit better :) 
I'll follow issue #102 thanks :)

**Comment by joffrey-bion** [comment] 2021-09-14 12:00
About the current issue, is there anything I could do in Krossbow to make the problem easier to understand and solve?

If not, I'll close this issue as it's not really a problem with Krossbow itself, but rather a configuration/server problem.

**Comment by yunjaena** [comment] 2021-09-14 12:08
I think we can handle this issue from OkHttpClient :)

**Closed** 2021-09-14 12:32 UTC
Labels: bug
